#!/usr/bin/env bash

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
THEME_HOME="${THEME_HOME:-$SCRIPT_DIR/themes}"
THEME_LIBRARY_DIR="${THEME_LIBRARY_DIR:-$THEME_HOME/color_themes}"
THEME_STATE_DIR="${THEME_STATE_DIR:-$HOME/.local/state/quickshell-theme}"
THEME_PREVIEW_DIR="${THEME_PREVIEW_DIR:-$THEME_STATE_DIR/previews}"
THEME_RUNTIME_DIR="${THEME_RUNTIME_DIR:-$THEME_STATE_DIR/runtime}"
THEME_CURRENT_DIR="${THEME_CURRENT_DIR:-$THEME_STATE_DIR/current}"
THEME_CURRENT_VIDEO_LINK="${THEME_CURRENT_VIDEO_LINK:-$THEME_CURRENT_DIR/video.mp4}"
THEME_CURRENT_FRAME_FILE="${THEME_CURRENT_FRAME_FILE:-$THEME_CURRENT_DIR/frame.png}"
THEME_CURRENT_NAME_FILE="${THEME_CURRENT_NAME_FILE:-$THEME_STATE_DIR/current-theme-name}"
THEME_CURRENT_DIR_FILE="${THEME_CURRENT_DIR_FILE:-$THEME_STATE_DIR/current-theme-dir}"
NIRI_CONFIG_FILE="${NIRI_CONFIG_FILE:-$HOME/.config/niri/config.kdl}"
NIRI_ANIMATIONS_ROOT="${NIRI_ANIMATIONS_ROOT:-$HOME/.config/niri/animations}"
NIRI_ANIMATION_STATE_FILE="${NIRI_ANIMATION_STATE_FILE:-$THEME_STATE_DIR/current-animation}"

theme_ensure_runtime_dirs() {
	mkdir -p "$THEME_STATE_DIR" "$THEME_PREVIEW_DIR" "$THEME_RUNTIME_DIR" "$THEME_CURRENT_DIR"
}
